<?php
$translations = [
    'actions.close' => ['en' => 'Close', 'fr' => 'Fermer'],
    'auth.ui.email_alternative_text'  => ['en' => 'If the button does not work, copy this link:', 'fr' => 'Si le bouton ne fonctionne pas, copiez ce lien :'],
    'auth.ui.email_body_line1'        => ['en' => 'You requested a password reset.', 'fr' => 'Vous avez demandé une réinitialisation de mot de passe.'],
    'auth.ui.email_body_line2'        => ['en' => 'Click the button below to reset your password.', 'fr' => 'Cliquez sur le bouton ci-dessous pour réinitialiser votre mot de passe.'],
    'auth.ui.email_button'            => ['en' => 'Reset my password', 'fr' => 'Réinitialiser mon mot de passe'],
    'auth.ui.email_closing'           => ['en' => 'Best regards,', 'fr' => 'Cordialement,'],
    'auth.ui.email_expiry_text'       => ['en' => 'This link expires in 60 minutes.', 'fr' => 'Ce lien expire dans 60 minutes.'],
    'auth.ui.email_expiry_title'      => ['en' => 'Link expiry', 'fr' => 'Expiration du lien'],
    'auth.ui.email_footer_line1'      => ['en' => 'If you did not request this reset, ignore this email.', 'fr' => 'Si vous n\'avez pas demandé cette réinitialisation, ignorez cet e-mail.'],
    'auth.ui.email_footer_line2'      => ['en' => 'Your account remains secure.', 'fr' => 'Votre compte reste sécurisé.'],
    'auth.ui.email_greeting'          => ['en' => 'Hello,', 'fr' => 'Bonjour,'],
    'auth.ui.email_help_text'         => ['en' => 'Need help? Contact support.', 'fr' => 'Besoin d\'aide ? Contactez le support.'],
    'auth.ui.email_security_text'     => ['en' => 'For security reasons, this link can only be used once.', 'fr' => 'Pour des raisons de sécurité, ce lien ne peut être utilisé qu\'une seule fois.'],
    'auth.ui.email_security_title'    => ['en' => 'Security', 'fr' => 'Sécurité'],
    'auth.ui.email_subject'           => ['en' => 'Password reset', 'fr' => 'Réinitialisation de mot de passe'],
    'auth.ui.email_team'              => ['en' => 'The LocaGed team', 'fr' => 'L\'équipe LocaGed'],
    'auth.ui.email_title'             => ['en' => 'Password reset', 'fr' => 'Réinitialisation de mot de passe'],
    'errors.physical_location.box_update_failed' => ['en' => 'Failed to update the box.', 'fr' => 'Échec de la mise à jour de la boîte.'],
    'filters.box_search'        => ['en' => 'Search box', 'fr' => 'Rechercher une boîte'],
    'filters.categories_short'  => ['en' => 'Category', 'fr' => 'Catégorie'],
    'filters.favorites_only'    => ['en' => 'Favorites only', 'fr' => 'Favoris uniquement'],
    'filters.file_type'         => ['en' => 'File type', 'fr' => 'Type de fichier'],
    'filters.from'              => ['en' => 'From', 'fr' => 'Du'],
    'filters.per_page'          => ['en' => 'Per page', 'fr' => 'Par page'],
    'filters.reset_filters'     => ['en' => 'Reset filters', 'fr' => 'Réinitialiser les filtres'],
    'filters.to'                => ['en' => 'To', 'fr' => 'Au'],
    'filters.types.audio'       => ['en' => 'Audio', 'fr' => 'Audio'],
    'filters.types.doc'         => ['en' => 'Document', 'fr' => 'Document'],
    'filters.types.excel'       => ['en' => 'Excel', 'fr' => 'Excel'],
    'filters.types.image'       => ['en' => 'Image', 'fr' => 'Image'],
    'filters.types.pdf'         => ['en' => 'PDF', 'fr' => 'PDF'],
    'filters.types.video'       => ['en' => 'Video', 'fr' => 'Vidéo'],
    'filters.types.word'        => ['en' => 'Word', 'fr' => 'Word'],
    'filters.without_category'  => ['en' => 'Without category', 'fr' => 'Sans catégorie'],
    'header.favorites'          => ['en' => 'Favorites', 'fr' => 'Favoris'],
    'messages.physical_location.room_contains_documents' => ['en' => 'This room contains documents and cannot be deleted.', 'fr' => 'Cette salle contient des documents et ne peut pas être supprimée.'],
    'messages.physical_location.room_deleted'            => ['en' => 'Room deleted.', 'fr' => 'Salle supprimée.'],
    'nav.all_documents'     => ['en' => 'All documents', 'fr' => 'Tous les documents'],
    'nav.destruction'       => ['en' => 'Destruction', 'fr' => 'Destruction'],
    'nav.localization'      => ['en' => 'Localization', 'fr' => 'Localisation'],
    'nav.ocr'               => ['en' => 'OCR', 'fr' => 'OCR'],
    'nav.physical_location' => ['en' => 'Physical location', 'fr' => 'Emplacement physique'],
    'nav.upload'            => ['en' => 'Upload', 'fr' => 'Dépôt'],
    'pages.actions.bulk_delete'       => ['en' => 'Delete selected', 'fr' => 'Supprimer la sélection'],
    'pages.actions.delete_permanently'=> ['en' => 'Delete permanently', 'fr' => 'Supprimer définitivement'],
    'pages.activity.actions.'                    => ['en' => '', 'fr' => ''],
    'pages.activity.actions.approved'            => ['en' => 'Approved', 'fr' => 'Approuvé'],
    'pages.activity.actions.archived'            => ['en' => 'Archived', 'fr' => 'Archivé'],
    'pages.activity.actions.archiving_confirmed' => ['en' => 'Archiving confirmed', 'fr' => 'Archivage confirmé'],
    'pages.activity.actions.borrowed'            => ['en' => 'Borrowed', 'fr' => 'Emprunté'],
    'pages.activity.actions.category_created'    => ['en' => 'Category created', 'fr' => 'Catégorie créée'],
    'pages.activity.actions.category_deleted'    => ['en' => 'Category deleted', 'fr' => 'Catégorie supprimée'],
    'pages.activity.actions.category_updated'    => ['en' => 'Category updated', 'fr' => 'Catégorie mise à jour'],
    'pages.activity.actions.created'             => ['en' => 'Created', 'fr' => 'Créé'],
    'pages.activity.actions.declined'            => ['en' => 'Declined', 'fr' => 'Refusé'],
    'pages.activity.actions.document_resubmitted'           => ['en' => 'Resubmitted', 'fr' => 'Resoumis'],
    'pages.activity.actions.document_submitted_for_review'  => ['en' => 'Submitted for review', 'fr' => 'Soumis pour approbation'],
    'pages.activity.actions.download'            => ['en' => 'Downloaded', 'fr' => 'Téléchargé'],
    'pages.activity.actions.expiration_postponed'=> ['en' => 'Expiration postponed', 'fr' => 'Expiration reportée'],
    'pages.activity.actions.export_downloaded'   => ['en' => 'Export downloaded', 'fr' => 'Export téléchargé'],
    'pages.activity.actions.export_requested'    => ['en' => 'Export requested', 'fr' => 'Export demandé'],
    'pages.activity.actions.metadata_updated'    => ['en' => 'Metadata updated', 'fr' => 'Métadonnées mises à jour'],
    'pages.activity.actions.moved'               => ['en' => 'Moved', 'fr' => 'Déplacé'],
    'pages.activity.actions.permanently_deleted' => ['en' => 'Permanently deleted', 'fr' => 'Supprimé définitivement'],
    'pages.activity.actions.renamed'             => ['en' => 'Renamed', 'fr' => 'Renommé'],
    'pages.activity.actions.returned'            => ['en' => 'Returned', 'fr' => 'Retourné'],
    'pages.activity.actions.reviewer_assigned'   => ['en' => 'Reviewer assigned', 'fr' => 'Approbateur assigné'],
    'pages.activity.actions.reviewer_validated'  => ['en' => 'Reviewer validated', 'fr' => 'Approbateur validé'],
    'pages.activity.actions.sent_back_to_draft'  => ['en' => 'Sent back to draft', 'fr' => 'Renvoyé en brouillon'],
    'pages.activity.actions.user_role_changed'   => ['en' => 'Role changed', 'fr' => 'Rôle modifié'],
    'pages.activity.actions.user_updated'        => ['en' => 'User updated', 'fr' => 'Utilisateur mis à jour'],
    'pages.activity.actions.viewed'              => ['en' => 'Viewed', 'fr' => 'Consulté'],
    'pages.activity.cards.active_users'          => ['en' => 'Active users', 'fr' => 'Utilisateurs actifs'],
    'pages.activity.cards.this_week'             => ['en' => 'This week', 'fr' => 'Cette semaine'],
    'pages.activity.cards.todays_logs'           => ['en' => "Today's logs", 'fr' => 'Logs du jour'],
    'pages.activity.cards.total_logs'            => ['en' => 'Total logs', 'fr' => 'Total des logs'],
    'pages.activity.empty'                       => ['en' => 'No activity.', 'fr' => 'Aucune activité.'],
    'pages.activity.filters.action_type'         => ['en' => 'Action type', 'fr' => "Type d'action"],
    'pages.activity.filters.all_departments'     => ['en' => 'All departments', 'fr' => 'Tous les pôles'],
    'pages.activity.filters.all_users'           => ['en' => 'All users', 'fr' => 'Tous les utilisateurs'],
    'pages.activity.filters.date_from'           => ['en' => 'From', 'fr' => 'Du'],
    'pages.activity.filters.date_to'             => ['en' => 'To', 'fr' => 'Au'],
    'pages.activity.filters.department'          => ['en' => 'Department', 'fr' => 'Pôle'],
    'pages.activity.filters.export'              => ['en' => 'Export', 'fr' => 'Exporter'],
    'pages.activity.filters.per_page'            => ['en' => 'Per page', 'fr' => 'Par page'],
    'pages.activity.filters.search_placeholder'  => ['en' => 'Search…', 'fr' => 'Rechercher…'],
    'pages.activity.reset_filters'               => ['en' => 'Reset filters', 'fr' => 'Réinitialiser les filtres'],
    'pages.activity.table.date_time'             => ['en' => 'Date / Time', 'fr' => 'Date / Heure'],
    'pages.activity.table.ip_device'             => ['en' => 'IP / Device', 'fr' => 'IP / Appareil'],
    'pages.activity.table.na'                    => ['en' => 'N/A', 'fr' => 'N/A'],
    'pages.activity.tabs.authentication_activity'=> ['en' => 'Authentication', 'fr' => 'Authentification'],
    'pages.activity.tabs.document_activity'      => ['en' => 'Documents', 'fr' => 'Documents'],
    'pages.activity_log.active_users_30d'        => ['en' => 'Active users (30 days)', 'fr' => 'Utilisateurs actifs (30 jours)'],
    'pages.activity_log.activity_log'            => ['en' => 'Activity log', 'fr' => "Journal d'activité"],
    'pages.activity_log.are_you_sure'            => ['en' => 'Are you sure?', 'fr' => 'Êtes-vous sûr ?'],
    'pages.activity_log.cannot_undo'             => ['en' => 'This action cannot be undone.', 'fr' => 'Cette action est irréversible.'],
    'pages.activity_log.new_today'               => ['en' => 'New today', 'fr' => "Nouveau aujourd'hui"],
    'pages.activity_log.user_audit_title'        => ['en' => 'User audit', 'fr' => 'Audit utilisateur'],
    'pages.all_departments'     => ['en' => 'All departments', 'fr' => 'Tous les pôles'],
    'pages.back_to_departments' => ['en' => 'Back to departments', 'fr' => 'Retour aux pôles'],
    'pages.categories_edit.add_new_subcategory'  => ['en' => 'Add subcategory', 'fr' => 'Ajouter une sous-catégorie'],
    'pages.categories_edit.category_preview'     => ['en' => 'Preview', 'fr' => 'Aperçu'],
    'pages.categories_edit.days'                 => ['en' => 'Days', 'fr' => 'Jours'],
    'pages.categories_edit.enter_category'       => ['en' => 'Category name', 'fr' => 'Nom de la catégorie'],
    'pages.categories_edit.enter_category_ph'    => ['en' => 'e.g. Contracts', 'fr' => 'ex. Contrats'],
    'pages.categories_edit.enter_subcategories'  => ['en' => 'Subcategories', 'fr' => 'Sous-catégories'],
    'pages.categories_edit.expiry_unit'          => ['en' => 'Unit', 'fr' => 'Unité'],
    'pages.categories_edit.expiry_value'         => ['en' => 'Duration', 'fr' => 'Durée'],
    'pages.categories_edit.live_preview'         => ['en' => 'Live preview', 'fr' => 'Aperçu en direct'],
    'pages.categories_edit.months'               => ['en' => 'Months', 'fr' => 'Mois'],
    'pages.categories_edit.remove_subcategory'   => ['en' => 'Remove', 'fr' => 'Retirer'],
    'pages.categories_edit.select_service'       => ['en' => 'Select service', 'fr' => 'Sélectionner un service'],
    'pages.categories_edit.select_sub_department'=> ['en' => 'Select sub-department', 'fr' => 'Sélectionner une sous-structure'],
    'pages.categories_edit.select_unit'          => ['en' => 'Select unit', 'fr' => 'Sélectionner une unité'],
    'pages.categories_edit.subtitle'             => ['en' => 'Edit category', 'fr' => 'Modifier la catégorie'],
    'pages.categories_edit.years'                => ['en' => 'Years', 'fr' => 'Ans'],
    'pages.categories_form.add_new_subcategory'  => ['en' => 'Add subcategory', 'fr' => 'Ajouter une sous-catégorie'],
    'pages.categories_form.category_preview'     => ['en' => 'Preview', 'fr' => 'Aperçu'],
    'pages.categories_form.days'                 => ['en' => 'Days', 'fr' => 'Jours'],
    'pages.categories_form.enter_category'       => ['en' => 'Category name', 'fr' => 'Nom de la catégorie'],
    'pages.categories_form.enter_category_ph'    => ['en' => 'e.g. Contracts', 'fr' => 'ex. Contrats'],
    'pages.categories_form.enter_subcategory'    => ['en' => 'Subcategory name', 'fr' => 'Nom de la sous-catégorie'],
    'pages.categories_form.expiry_unit'          => ['en' => 'Unit', 'fr' => 'Unité'],
    'pages.categories_form.expiry_value'         => ['en' => 'Duration', 'fr' => 'Durée'],
    'pages.categories_form.expiry_value_example' => ['en' => 'e.g. 5', 'fr' => 'ex. 5'],
    'pages.categories_form.live_preview'         => ['en' => 'Live preview', 'fr' => 'Aperçu en direct'],
    'pages.categories_form.months'               => ['en' => 'Months', 'fr' => 'Mois'],
    'pages.categories_form.optional'             => ['en' => 'Optional', 'fr' => 'Optionnel'],
    'pages.categories_form.remove_subcategory'   => ['en' => 'Remove', 'fr' => 'Retirer'],
    'pages.categories_form.select_unit'          => ['en' => 'Select unit', 'fr' => 'Sélectionner une unité'],
    'pages.categories_form.subtitle'             => ['en' => 'Create category', 'fr' => 'Créer une catégorie'],
    'pages.categories_form.years'                => ['en' => 'Years', 'fr' => 'Ans'],
    'pages.categories_in'                        => ['en' => 'Categories in', 'fr' => 'Catégories dans'],
    'pages.categories_page.all_categories'       => ['en' => 'All categories', 'fr' => 'Toutes les catégories'],
    'pages.categories_page.confirm'              => ['en' => 'Confirm', 'fr' => 'Confirmer'],
    'pages.categories_page.delete_body'          => ['en' => 'Delete this category permanently?', 'fr' => 'Supprimer définitivement cette catégorie ?'],
    'pages.categories_page.delete_title'         => ['en' => 'Delete category', 'fr' => 'Supprimer la catégorie'],
    'pages.categories_page.edit_category'        => ['en' => 'Edit category', 'fr' => 'Modifier la catégorie'],
    'pages.categories_page.open_category_subcategories' => ['en' => 'View subcategories', 'fr' => 'Voir les sous-catégories'],
    'pages.categories_page.open_subcategory'     => ['en' => 'Open subcategory', 'fr' => 'Ouvrir la sous-catégorie'],
    'pages.categories_page.subcategories'        => ['en' => 'Subcategories', 'fr' => 'Sous-catégories'],
    'pages.categories_page.view_subcategories'   => ['en' => 'View subcategories', 'fr' => 'Voir les sous-catégories'],
    'pages.categories_sub.add_subcategories'     => ['en' => 'Add subcategory', 'fr' => 'Ajouter une sous-catégorie'],
    'pages.categories_sub.all_categories'        => ['en' => 'All categories', 'fr' => 'Toutes les catégories'],
    'pages.categories_sub.confirm'               => ['en' => 'Confirm', 'fr' => 'Confirmer'],
    'pages.categories_sub.delete_body'           => ['en' => 'Delete this subcategory permanently?', 'fr' => 'Supprimer définitivement cette sous-catégorie ?'],
    'pages.categories_sub.delete_title'          => ['en' => 'Delete subcategory', 'fr' => 'Supprimer la sous-catégorie'],
    'pages.categories_sub.documents'             => ['en' => 'Documents', 'fr' => 'Documents'],
    'pages.categories_sub.files'                 => ['en' => 'Files', 'fr' => 'Fichiers'],
    'pages.categories_sub.no_subcategories'      => ['en' => 'No subcategories.', 'fr' => 'Aucune sous-catégorie.'],
    'pages.categories_sub.no_subcategories_hint' => ['en' => 'Create the first subcategory.', 'fr' => 'Créez la première sous-catégorie.'],
    'pages.category_fields.'                     => ['en' => '', 'fr' => ''],
    'pages.chart.all_status'    => ['en' => 'All statuses', 'fr' => 'Tous les statuts'],
    'pages.chart.approved'      => ['en' => 'Approved', 'fr' => 'Approuvé'],
    'pages.chart.days.fri'      => ['en' => 'Fri', 'fr' => 'Ven'],
    'pages.chart.days.mon'      => ['en' => 'Mon', 'fr' => 'Lun'],
    'pages.chart.days.sat'      => ['en' => 'Sat', 'fr' => 'Sam'],
    'pages.chart.days.sun'      => ['en' => 'Sun', 'fr' => 'Dim'],
    'pages.chart.days.thu'      => ['en' => 'Thu', 'fr' => 'Jeu'],
    'pages.chart.days.tue'      => ['en' => 'Tue', 'fr' => 'Mar'],
    'pages.chart.days.wed'      => ['en' => 'Wed', 'fr' => 'Mer'],
    'pages.chart.expired'       => ['en' => 'Expired', 'fr' => 'Expiré'],
    'pages.chart.monthly'       => ['en' => 'Monthly', 'fr' => 'Mensuel'],
    'pages.chart.no_data'       => ['en' => 'No data.', 'fr' => 'Aucune donnée.'],
    'pages.chart.pending'       => ['en' => 'Pending', 'fr' => 'En attente'],
    'pages.chart.statistics'    => ['en' => 'Statistics', 'fr' => 'Statistiques'],
    'pages.chart.summary_approvals' => ['en' => 'Approval summary', 'fr' => 'Résumé des approbations'],
    'pages.chart.weekly'        => ['en' => 'Weekly', 'fr' => 'Hebdomadaire'],
    'pages.chart.yearly'        => ['en' => 'Yearly', 'fr' => 'Annuel'],
    'pages.dashboard.approvals'                   => ['en' => 'Approvals', 'fr' => 'Approbations'],
    'pages.dashboard.donut.categories_in'         => ['en' => 'Categories in', 'fr' => 'Catégories dans'],
    'pages.dashboard.donut.categories_title'      => ['en' => 'Categories', 'fr' => 'Catégories'],
    'pages.dashboard.donut.departments_click'     => ['en' => 'Click a department', 'fr' => 'Cliquez sur un pôle'],
    'pages.dashboard.donut.departments_title'     => ['en' => 'Documents by department', 'fr' => 'Documents par pôle'],
    'pages.dashboard.donut.no_data'               => ['en' => 'No data.', 'fr' => 'Aucune donnée.'],
    'pages.dashboard.donut.no_documents'          => ['en' => 'No documents.', 'fr' => 'Aucun document.'],
    'pages.dashboard.donut.services_click'        => ['en' => 'Click a service', 'fr' => 'Cliquez sur un service'],
    'pages.dashboard.donut.services_empty'        => ['en' => 'No services.', 'fr' => 'Aucun service.'],
    'pages.dashboard.donut.services_title'        => ['en' => 'Documents by service', 'fr' => 'Documents par service'],
    'pages.dashboard.donut.sub_departments_click' => ['en' => 'Click a sub-department', 'fr' => 'Cliquez sur une sous-structure'],
    'pages.dashboard.donut.sub_departments_title' => ['en' => 'Documents by sub-department', 'fr' => 'Documents par sous-structure'],
    'pages.dashboard.overview'                    => ['en' => 'Overview', 'fr' => "Vue d'ensemble"],
    'pages.deletion_log.document_deleted'         => ['en' => 'Deleted', 'fr' => 'Supprimé'],
    'pages.deletion_log.export.creation_date'     => ['en' => 'Creation date', 'fr' => 'Date de création'],
    'pages.deletion_log.export.deleted_by'        => ['en' => 'Deleted by', 'fr' => 'Supprimé par'],
    'pages.deletion_log.export.deleted_on'        => ['en' => 'Deleted on', 'fr' => 'Supprimé le'],
    'pages.deletion_log.export.department'        => ['en' => 'Department', 'fr' => 'Pôle'],
    'pages.deletion_log.export.document_id'       => ['en' => 'ID', 'fr' => 'ID'],
    'pages.deletion_log.export.document_title'    => ['en' => 'Title', 'fr' => 'Titre'],
    'pages.deletion_log.export.expiration_date'   => ['en' => 'Expiration', 'fr' => 'Expiration'],
    'pages.deletion_log.export.generated_on'      => ['en' => 'Generated on', 'fr' => 'Généré le'],
    'pages.deletion_log.export.pole'              => ['en' => 'Pole', 'fr' => 'Pôle'],
    'pages.deletion_log.export.service'           => ['en' => 'Service', 'fr' => 'Service'],
    'pages.deletion_log.export.title'             => ['en' => 'Deletion log', 'fr' => 'Journal des destructions'],
    'pages.deletion_log.export.total_deletions'   => ['en' => 'Total deletions', 'fr' => 'Total destructions'],
    'pages.deletion_log.export_pdf'               => ['en' => 'Export PDF', 'fr' => 'Exporter PDF'],
    'pages.deletion_log.filters.all'              => ['en' => 'All', 'fr' => 'Tous'],
    'pages.deletion_log.filters.all_users'        => ['en' => 'All users', 'fr' => 'Tous les utilisateurs'],
    'pages.deletion_log.filters.creation_date'    => ['en' => 'Creation date', 'fr' => 'Date de création'],
    'pages.deletion_log.filters.deleted_at'       => ['en' => 'Deleted on', 'fr' => 'Supprimé le'],
    'pages.deletion_log.filters.deleted_by'       => ['en' => 'Deleted by', 'fr' => 'Supprimé par'],
    'pages.deletion_log.filters.document'         => ['en' => 'Document', 'fr' => 'Document'],
    'pages.deletion_log.filters.expiration'       => ['en' => 'Expiration', 'fr' => 'Expiration'],
    'pages.deletion_log.filters.export'           => ['en' => 'Export', 'fr' => 'Exporter'],
    'pages.deletion_log.filters.per_page'         => ['en' => 'Per page', 'fr' => 'Par page'],
    'pages.deletion_log.filters.reset'            => ['en' => 'Reset', 'fr' => 'Réinitialiser'],
    'pages.deletion_log.filters.search_placeholder'=> ['en' => 'Search…', 'fr' => 'Rechercher…'],
    'pages.deletion_log.filters.structure'        => ['en' => 'Structure', 'fr' => 'Structure'],
    'pages.deletion_log.no_documents'             => ['en' => 'No documents.', 'fr' => 'Aucun document.'],
    'pages.deletion_log.stats.this_week'          => ['en' => 'This week', 'fr' => 'Cette semaine'],
    'pages.deletion_log.stats.today'              => ['en' => 'Today', 'fr' => "Aujourd'hui"],
    'pages.deletion_log.stats.total_deleted'      => ['en' => 'Total deleted', 'fr' => 'Total supprimé'],
    'pages.deletion_log.table.creation_date'      => ['en' => 'Creation date', 'fr' => 'Date de création'],
    'pages.deletion_log.table.deleted_at'         => ['en' => 'Deleted on', 'fr' => 'Supprimé le'],
    'pages.deletion_log.table.deleted_by'         => ['en' => 'Deleted by', 'fr' => 'Supprimé par'],
    'pages.deletion_log.table.document'           => ['en' => 'Document', 'fr' => 'Document'],
    'pages.deletion_log.table.expiration'         => ['en' => 'Expiration', 'fr' => 'Expiration'],
    'pages.deletion_log.table.pdf'                => ['en' => 'PDF', 'fr' => 'PDF'],
    'pages.deletion_log.table.structure'          => ['en' => 'Structure', 'fr' => 'Structure'],
    'pages.destructions.actions'                  => ['en' => 'Actions', 'fr' => 'Actions'],
    'pages.destructions.author'                   => ['en' => 'Author', 'fr' => 'Auteur'],
    'pages.destructions.created_by'               => ['en' => 'Created by', 'fr' => 'Créé par'],
    'pages.destructions.creation_date'            => ['en' => 'Creation date', 'fr' => 'Date de création'],
    'pages.destructions.delete_button'            => ['en' => 'Destroy', 'fr' => 'Détruire'],
    'pages.destructions.document_name'            => ['en' => 'Document', 'fr' => 'Document'],
    'pages.destructions.expiration_date'          => ['en' => 'Expiration', 'fr' => 'Expiration'],
    'pages.destructions.export'                   => ['en' => 'Export', 'fr' => 'Exporter'],
    'pages.destructions.no_expired_documents'     => ['en' => 'No expired documents.', 'fr' => 'Aucun document expiré.'],
    'pages.destructions.postpone.'                => ['en' => '', 'fr' => ''],
    'pages.destructions.postpone.amount_label'    => ['en' => 'Duration', 'fr' => 'Durée'],
    'pages.destructions.postpone.amount_placeholder'=> ['en' => 'e.g. 6', 'fr' => 'ex. 6'],
    'pages.destructions.postpone.confirm_button'  => ['en' => 'Confirm', 'fr' => 'Confirmer'],
    'pages.destructions.postpone.days'            => ['en' => 'Days', 'fr' => 'Jours'],
    'pages.destructions.postpone.description'     => ['en' => 'Postpone the destruction of this document.', 'fr' => 'Reporter la destruction de ce document.'],
    'pages.destructions.postpone.months'          => ['en' => 'Months', 'fr' => 'Mois'],
    'pages.destructions.postpone.success'         => ['en' => 'Expiration postponed.', 'fr' => 'Expiration reportée.'],
    'pages.destructions.postpone.success_active'  => ['en' => 'Expiration updated.', 'fr' => 'Expiration mise à jour.'],
    'pages.destructions.postpone.time_unit'       => ['en' => 'Unit', 'fr' => 'Unité'],
    'pages.destructions.postpone.title'           => ['en' => 'Postpone destruction', 'fr' => 'Reporter la destruction'],
    'pages.destructions.postpone.weeks'           => ['en' => 'Weeks', 'fr' => 'Semaines'],
    'pages.destructions.postpone.years'           => ['en' => 'Years', 'fr' => 'Ans'],
    'pages.destructions.postpone_button'          => ['en' => 'Postpone', 'fr' => 'Reporter'],
    'pages.destructions.preview'                  => ['en' => 'Preview', 'fr' => 'Aperçu'],
    'pages.destructions.request_deleted'          => ['en' => 'Request deleted.', 'fr' => 'Demande supprimée.'],
    'pages.destructions.status'                   => ['en' => 'Status', 'fr' => 'Statut'],
    'pages.destructions.status_values.expired'    => ['en' => 'Expired', 'fr' => 'Expiré'],
    'pages.document_detail.embedded_unavailable'  => ['en' => 'Preview unavailable.', 'fr' => 'Aperçu non disponible.'],
    'pages.document_detail.full_preview'          => ['en' => 'Full preview', 'fr' => 'Aperçu complet'],
    'pages.document_detail.hash'                  => ['en' => 'Hash', 'fr' => 'Empreinte'],
    'pages.document_detail.hash_empty'            => ['en' => 'Not computed.', 'fr' => 'Non calculée.'],
    'pages.document_detail.preview'               => ['en' => 'Preview', 'fr' => 'Aperçu'],
    'pages.document_detail.status_change'         => ['en' => 'Status change', 'fr' => 'Changement de statut'],
    'pages.document_detail.structure'             => ['en' => 'Structure', 'fr' => 'Structure'],
    'pages.document_detail.submitted'             => ['en' => 'Submitted', 'fr' => 'Soumis'],
    'pages.document_detail.timeline'              => ['en' => 'Timeline', 'fr' => 'Historique'],
    'pages.document_detail.versions_section'      => ['en' => 'Versions', 'fr' => 'Versions'],
    'pages.documents.approve_body'                => ['en' => 'Approve this document?', 'fr' => 'Approuver ce document ?'],
    'pages.documents.approve_title'               => ['en' => 'Approve', 'fr' => 'Approuver'],
    'pages.documents.bulk_permanent_delete_confirm'=> ['en' => 'Permanently delete selected documents?', 'fr' => 'Supprimer définitivement les documents sélectionnés ?'],
    'pages.documents.cancel'                      => ['en' => 'Cancel', 'fr' => 'Annuler'],
    'pages.documents.delete_success'              => ['en' => 'Document deleted.', 'fr' => 'Document supprimé.'],
    'pages.documents.favorite.add'                => ['en' => 'Add to favorites', 'fr' => 'Ajouter aux favoris'],
    'pages.documents.favorite.label'              => ['en' => 'Favorite', 'fr' => 'Favori'],
    'pages.documents.favorite.remove'             => ['en' => 'Remove from favorites', 'fr' => 'Retirer des favoris'],
    'pages.documents.filetype.'                   => ['en' => '', 'fr' => ''],
    'pages.documents.move.borrower_name'          => ['en' => 'Borrower name', 'fr' => "Nom de l'emprunteur"],
    'pages.documents.move.confirm'                => ['en' => 'Confirm', 'fr' => 'Confirmer'],
    'pages.documents.move.current_location_hint'  => ['en' => 'Current location', 'fr' => 'Emplacement actuel'],
    'pages.documents.move.description'            => ['en' => 'Move this document to a new physical location.', 'fr' => 'Déplacer ce document vers un nouvel emplacement physique.'],
    'pages.documents.move.due_at'                 => ['en' => 'Return date', 'fr' => 'Date de retour'],
    'pages.documents.move.first_select_room'      => ['en' => 'Select a room first.', 'fr' => "Sélectionnez d'abord une salle."],
    'pages.documents.move.first_select_row'       => ['en' => 'Select a row first.', 'fr' => "Sélectionnez d'abord une rangée."],
    'pages.documents.move.first_select_shelf'     => ['en' => 'Select a shelf first.', 'fr' => "Sélectionnez d'abord une étagère."],
    'pages.documents.move.moved_from'             => ['en' => 'Moved from', 'fr' => 'Déplacé depuis'],
    'pages.documents.move.moved_to'               => ['en' => 'Moved to', 'fr' => 'Déplacé vers'],
    'pages.documents.move.movement_type'          => ['en' => 'Movement type', 'fr' => 'Type de mouvement'],
    'pages.documents.move.movement_type_options.' => ['en' => '', 'fr' => ''],
    'pages.documents.move.no_location_assigned'   => ['en' => 'No location assigned.', 'fr' => 'Aucun emplacement assigné.'],
    'pages.documents.move.no_location_hint'       => ['en' => 'Assign a physical location.', 'fr' => 'Assignez un emplacement physique.'],
    'pages.documents.move.room'                   => ['en' => 'Room', 'fr' => 'Salle'],
    'pages.documents.move.select_type'            => ['en' => 'Select type', 'fr' => 'Sélectionner le type'],
    'pages.documents.permanent_delete_body'       => ['en' => 'Permanently delete this document?', 'fr' => 'Supprimer définitivement ce document ?'],
    'pages.documents.permanent_delete_hint'       => ['en' => 'This action cannot be undone.', 'fr' => 'Cette action est irréversible.'],
    'pages.documents.permanent_delete_title'      => ['en' => 'Permanent deletion', 'fr' => 'Suppression définitive'],
    'pages.documents.preview'                     => ['en' => 'Preview', 'fr' => 'Aperçu'],
    'pages.documents.reject_body'                 => ['en' => 'Decline this document?', 'fr' => 'Refuser ce document ?'],
    'pages.documents.reject_title'                => ['en' => 'Decline', 'fr' => 'Refuser'],
    'pages.documents.rename_body'                 => ['en' => 'Enter a new name for this document.', 'fr' => 'Entrez un nouveau nom pour ce document.'],
    'pages.documents.rename_button'               => ['en' => 'Rename', 'fr' => 'Renommer'],
    'pages.documents.rename_placeholder'          => ['en' => 'New name…', 'fr' => 'Nouveau nom…'],
    'pages.documents.rename_title'                => ['en' => 'Rename document', 'fr' => 'Renommer le document'],
    'pages.documents.request_destruction_button'  => ['en' => 'Request destruction', 'fr' => 'Demander la destruction'],
    'pages.documents.request_destruction_confirm' => ['en' => 'Confirm destruction request?', 'fr' => 'Confirmer la demande de destruction ?'],
    'pages.documents.request_destruction_title'   => ['en' => 'Request destruction', 'fr' => 'Demander la destruction'],
    'pages.documents.status.'                     => ['en' => '', 'fr' => ''],
    'pages.documents.status.expired'              => ['en' => 'Expired', 'fr' => 'Expiré'],
    'pages.documents.status.pending'              => ['en' => 'Pending', 'fr' => 'En attente'],
    'pages.error_loading_categories'              => ['en' => 'Error loading categories.', 'fr' => 'Erreur lors du chargement des catégories.'],
    'pages.errors.input_problems'                 => ['en' => 'Please fix the errors below.', 'fr' => 'Veuillez corriger les erreurs ci-dessous.'],
    'pages.file_audit'                            => ['en' => 'File audit', 'fr' => 'Audit des fichiers'],
    'pages.headings.'                             => ['en' => '', 'fr' => ''],
    'pages.loading'                               => ['en' => 'Loading…', 'fr' => 'Chargement…'],
    'pages.messages.confirm_icon'                 => ['en' => 'Confirm', 'fr' => 'Confirmer'],
    'pages.messages.no_unread_notifications'      => ['en' => 'No unread notifications.', 'fr' => 'Aucune notification non lue.'],
    'pages.no_categories'                         => ['en' => 'No categories.', 'fr' => 'Aucune catégorie.'],
    'pages.no_categories_in_dept'                 => ['en' => 'No categories in this department.', 'fr' => 'Aucune catégorie dans ce pôle.'],
    'pages.notifications.empty'                   => ['en' => 'No notifications.', 'fr' => 'Aucune notification.'],
    'pages.notifications.mark_all_as_read'        => ['en' => 'Mark all as read', 'fr' => 'Tout marquer comme lu'],
    'pages.notifications.marked_as_read'          => ['en' => 'Marked as read.', 'fr' => 'Marqué comme lu.'],
    'pages.notifications.notification'            => ['en' => 'Notification', 'fr' => 'Notification'],
    'pages.notifications.notification_panel'      => ['en' => 'Notifications', 'fr' => 'Notifications'],
    'pages.notifications.unread'                  => ['en' => 'Unread', 'fr' => 'Non lues'],
    'pages.notifications.view_all'                => ['en' => 'View all', 'fr' => 'Tout voir'],
    'pages.ocr.status.completed'                  => ['en' => 'Completed', 'fr' => 'Terminé'],
    'pages.ocr_jobs.status.'                      => ['en' => '', 'fr' => ''],
    'pages.ocr_view.audio_file'                   => ['en' => 'Audio file', 'fr' => 'Fichier audio'],
    'pages.ocr_view.audio_not_supported'          => ['en' => 'Audio not supported.', 'fr' => 'Audio non supporté.'],
    'pages.ocr_view.author'                       => ['en' => 'Author', 'fr' => 'Auteur'],
    'pages.ocr_view.creation_date'                => ['en' => 'Creation date', 'fr' => 'Date de création'],
    'pages.ocr_view.document_name'                => ['en' => 'Document', 'fr' => 'Document'],
    'pages.ocr_view.download'                     => ['en' => 'Download', 'fr' => 'Télécharger'],
    'pages.ocr_view.download_file'                => ['en' => 'Download file', 'fr' => 'Télécharger le fichier'],
    'pages.ocr_view.expire_date'                  => ['en' => 'Expiration date', 'fr' => "Date d'expiration"],
    'pages.ocr_view.extracted_text'               => ['en' => 'Extracted text', 'fr' => 'Texte extrait'],
    'pages.ocr_view.no_text_yet'                  => ['en' => 'No text extracted yet.', 'fr' => "Aucun texte extrait pour l'instant."],
    'pages.ocr_view.status'                       => ['en' => 'Status', 'fr' => 'Statut'],
    'pages.ocr_view.submit'                       => ['en' => 'Submit', 'fr' => 'Soumettre'],
    'pages.ocr_view.video_not_supported'          => ['en' => 'Video not supported.', 'fr' => 'Vidéo non supportée.'],
    'pages.physical.actions.edit'                 => ['en' => 'Edit', 'fr' => 'Modifier'],
    'pages.physical.box_help'                     => ['en' => 'Box identifier', 'fr' => 'Identifiant de la boîte'],
    'pages.physical.box_placeholder'              => ['en' => 'e.g. B-01', 'fr' => 'ex. B-01'],
    'pages.physical.fields.box'                   => ['en' => 'Box', 'fr' => 'Boîte'],
    'pages.physical.fields.room'                  => ['en' => 'Room', 'fr' => 'Salle'],
    'pages.physical.fields.row'                   => ['en' => 'Row', 'fr' => 'Rangée'],
    'pages.physical.fields.shelf'                 => ['en' => 'Shelf', 'fr' => 'Étagère'],
    'pages.physical.placeholders.room_example'    => ['en' => 'e.g. Archive Room A', 'fr' => 'ex. Salle Archives A'],
    'pages.physical.room_help'                    => ['en' => 'Room name or identifier', 'fr' => 'Nom ou identifiant de la salle'],
    'pages.physical.row_help'                     => ['en' => 'Row identifier', 'fr' => 'Identifiant de la rangée'],
    'pages.physical.row_placeholder'              => ['en' => 'e.g. R-01', 'fr' => 'ex. R-01'],
    'pages.physical.shelf_help'                   => ['en' => 'Shelf identifier', 'fr' => "Identifiant de l'étagère"],
    'pages.physical.shelf_placeholder'            => ['en' => 'e.g. E-01', 'fr' => 'ex. E-01'],
    'pages.physical_locations.box'                => ['en' => 'Box', 'fr' => 'Boîte'],
    'pages.profile.change_password_title'         => ['en' => 'Change password', 'fr' => 'Changer le mot de passe'],
    'pages.profile.confirm_new_password'          => ['en' => 'Confirm new password', 'fr' => 'Confirmer le nouveau mot de passe'],
    'pages.profile.my_profile'                    => ['en' => 'My profile', 'fr' => 'Mon profil'],
    'pages.profile.no_structures'                 => ['en' => 'No structures assigned.', 'fr' => 'Aucune structure assignée.'],
    'pages.profile.old_password'                  => ['en' => 'Current password', 'fr' => 'Mot de passe actuel'],
    'pages.profile.password'                      => ['en' => 'Password', 'fr' => 'Mot de passe'],
    'pages.profile.personal_info'                 => ['en' => 'Personal information', 'fr' => 'Informations personnelles'],
    'pages.profile.phone'                         => ['en' => 'Phone', 'fr' => 'Téléphone'],
    'pages.profile.role'                          => ['en' => 'Role', 'fr' => 'Rôle'],
    'pages.profile.structures'                    => ['en' => 'Structures', 'fr' => 'Structures'],
    'pages.profile.update'                        => ['en' => 'Update', 'fr' => 'Mettre à jour'],
    'pages.reports.apply'                         => ['en' => 'Apply', 'fr' => 'Appliquer'],
    'pages.reports.clear'                         => ['en' => 'Clear', 'fr' => 'Effacer'],
    'pages.reports.departments'                   => ['en' => 'Departments', 'fr' => 'Pôles'],
    'pages.reports.document_reports'              => ['en' => 'Document reports', 'fr' => 'Rapports documents'],
    'pages.reports.empty'                         => ['en' => 'No results.', 'fr' => 'Aucun résultat.'],
    'pages.reports.export_csv'                    => ['en' => 'Export CSV', 'fr' => 'Exporter CSV'],
    'pages.reports.filters.all_rooms'             => ['en' => 'All rooms', 'fr' => 'Toutes les salles'],
    'pages.reports.filters.all_users'             => ['en' => 'All users', 'fr' => 'Tous les utilisateurs'],
    'pages.reports.filters.all_years'             => ['en' => 'All years', 'fr' => 'Toutes les années'],
    'pages.reports.filters.room'                  => ['en' => 'Room', 'fr' => 'Salle'],
    'pages.reports.filters.user'                  => ['en' => 'User', 'fr' => 'Utilisateur'],
    'pages.reports.filters.year'                  => ['en' => 'Year', 'fr' => 'Année'],
    'pages.reports.search_placeholder'            => ['en' => 'Search…', 'fr' => 'Rechercher…'],
    'pages.reports.table.created_at'              => ['en' => 'Created at', 'fr' => 'Créé le'],
    'pages.reports.table.created_by'              => ['en' => 'Created by', 'fr' => 'Créé par'],
    'pages.reports.table.department'              => ['en' => 'Department', 'fr' => 'Pôle'],
    'pages.roles.confirm'                         => ['en' => 'Confirm', 'fr' => 'Confirmer'],
    'pages.roles.create'                          => ['en' => 'Create role', 'fr' => 'Créer un rôle'],
    'pages.roles.create_title'                    => ['en' => 'New role', 'fr' => 'Nouveau rôle'],
    'pages.roles.delete_body'                     => ['en' => 'Delete this role permanently?', 'fr' => 'Supprimer définitivement ce rôle ?'],
    'pages.roles.delete_title'                    => ['en' => 'Delete role', 'fr' => 'Supprimer le rôle'],
    'pages.roles.manage'                          => ['en' => 'Manage', 'fr' => 'Gérer'],
    'pages.roles.manage_permissions_for'          => ['en' => 'Manage permissions for', 'fr' => 'Gérer les permissions de'],
    'pages.roles.models.approve'                  => ['en' => 'Approve', 'fr' => 'Approuver'],
    'pages.roles.models.create'                   => ['en' => 'Create', 'fr' => 'Créer'],
    'pages.roles.models.decline'                  => ['en' => 'Decline', 'fr' => 'Refuser'],
    'pages.roles.models.delete'                   => ['en' => 'Delete', 'fr' => 'Supprimer'],
    'pages.roles.models.edit'                     => ['en' => 'Edit', 'fr' => 'Modifier'],
    'pages.roles.models.force_delete'             => ['en' => 'Force delete', 'fr' => 'Suppression forcée'],
    'pages.roles.models.model'                    => ['en' => 'Resource', 'fr' => 'Ressource'],
    'pages.roles.models.restore'                  => ['en' => 'Restore', 'fr' => 'Restaurer'],
    'pages.roles.models.update'                   => ['en' => 'Update', 'fr' => 'Modifier'],
    'pages.roles.models.view_any'                 => ['en' => 'View all', 'fr' => 'Voir tout'],
    'pages.roles.models.view_own'                 => ['en' => 'View own', 'fr' => 'Voir les siens'],
    'pages.roles.models.view_structure'           => ['en' => 'View structure', 'fr' => 'Voir la structure'],
    'pages.roles.placeholder_examples'            => ['en' => 'e.g. Editor, Reviewer…', 'fr' => 'ex. Éditeur, Vérificateur…'],
    'pages.roles.role_name'                       => ['en' => 'Role name', 'fr' => 'Nom du rôle'],
    'pages.roles.roles_btn'                       => ['en' => 'Roles', 'fr' => 'Rôles'],
    'pages.roles.save_permissions'                => ['en' => 'Save permissions', 'fr' => 'Enregistrer les permissions'],
    'pages.roles.select_all'                      => ['en' => 'Select all', 'fr' => 'Tout sélectionner'],
    'pages.roles.table.actions'                   => ['en' => 'Actions', 'fr' => 'Actions'],
    'pages.roles.table.created_at'                => ['en' => 'Created at', 'fr' => 'Créé le'],
    'pages.roles.table.name'                      => ['en' => 'Name', 'fr' => 'Nom'],
    'pages.roles.table.permissions'               => ['en' => 'Permissions', 'fr' => 'Permissions'],
    'pages.roles.table.updated_at'                => ['en' => 'Updated at', 'fr' => 'Mis à jour le'],
    'pages.roles.table.users'                     => ['en' => 'Users', 'fr' => 'Utilisateurs'],
    'pages.roles.users_btn'                       => ['en' => 'Users', 'fr' => 'Utilisateurs'],
    'pages.rooms_cards.docs'                      => ['en' => 'Docs', 'fr' => 'Docs'],
    'pages.rooms_cards.rooms'                     => ['en' => 'Rooms', 'fr' => 'Salles'],
    'pages.rooms_cards.see_more'                  => ['en' => 'See more', 'fr' => 'Voir plus'],
    'pages.rooms_cards.storage_by_room'           => ['en' => 'Storage by room', 'fr' => 'Stockage par salle'],
    'pages.services_in'                           => ['en' => 'Services in', 'fr' => 'Services dans'],
    'pages.services_of'                           => ['en' => 'Services of', 'fr' => 'Services de'],
    'pages.stats.all_documents'                   => ['en' => 'All documents', 'fr' => 'Tous les documents'],
    'pages.stats.approved'                        => ['en' => 'Approved', 'fr' => 'Approuvés'],
    'pages.stats.expired'                         => ['en' => 'Expired', 'fr' => 'Expirés'],
    'pages.stats.pending'                         => ['en' => 'Pending', 'fr' => 'En attente'],
    'pages.stats.todays_uploads'                  => ['en' => "Today's uploads", 'fr' => 'Dépôts du jour'],
    'pages.stats.total_documents'                 => ['en' => 'Total documents', 'fr' => 'Total documents'],
    'pages.status.title'                          => ['en' => 'Status', 'fr' => 'Statut'],
    'pages.storage.app_documents_description'     => ['en' => 'Space used by uploaded documents', 'fr' => 'Espace utilisé par les documents déposés'],
    'pages.storage.app_documents_usage'           => ['en' => 'Documents storage', 'fr' => 'Stockage documents'],
    'pages.storage.description'                   => ['en' => 'Server storage usage', 'fr' => 'Utilisation du stockage serveur'],
    'pages.storage.free'                          => ['en' => 'Free', 'fr' => 'Libre'],
    'pages.storage.server_disk_usage'             => ['en' => 'Server disk usage', 'fr' => 'Utilisation du disque serveur'],
    'pages.storage.share_of_total_disk'           => ['en' => 'Share of total disk', 'fr' => 'Part du disque total'],
    'pages.storage.share_of_used_space'           => ['en' => 'Share of used space', 'fr' => "Part de l'espace utilisé"],
    'pages.storage.size_used_by_documents'        => ['en' => 'Used by documents', 'fr' => 'Utilisé par les documents'],
    'pages.storage.status_critical'               => ['en' => 'Critical', 'fr' => 'Critique'],
    'pages.storage.status_normal'                 => ['en' => 'Normal', 'fr' => 'Normal'],
    'pages.storage.status_warning'                => ['en' => 'Warning', 'fr' => 'Avertissement'],
    'pages.storage.total_disk_space'              => ['en' => 'Total disk space', 'fr' => 'Espace disque total'],
    'pages.storage.unable_to_read'                => ['en' => 'Unable to read disk info.', 'fr' => 'Impossible de lire les informations disque.'],
    'pages.storage.values_calculated'             => ['en' => 'Values are calculated in real time.', 'fr' => 'Valeurs calculées en temps réel.'],
    'pages.structures_page.add'                   => ['en' => 'Add', 'fr' => 'Ajouter'],
    'pages.structures_page.add_button'            => ['en' => 'Add', 'fr' => 'Ajouter'],
    'pages.structures_page.description'           => ['en' => 'Description', 'fr' => 'Description'],
    'pages.structures_page.existing'              => ['en' => 'Existing', 'fr' => 'Existants'],
    'pages.structures_page.manage'                => ['en' => 'Manage', 'fr' => 'Gérer'],
    'pages.structures_page.placeholder_description'=> ['en' => 'Description (optional)', 'fr' => 'Description (optionnel)'],
    'pages.structures_page.placeholder_name'      => ['en' => 'Name', 'fr' => 'Nom'],
    'pages.structures_page.services_add_button'   => ['en' => 'Add service', 'fr' => 'Ajouter un service'],
    'pages.structures_page.services_name_label'   => ['en' => 'Service name', 'fr' => 'Nom du service'],
    'pages.structures_page.services_name_placeholder'=> ['en' => 'e.g. Accounting', 'fr' => 'ex. Comptabilité'],
    'pages.structures_page.services_title'        => ['en' => 'Services', 'fr' => 'Services'],
    'pages.structures_page.sub_departments_add_button'=> ['en' => 'Add sub-department', 'fr' => 'Ajouter une sous-structure'],
    'pages.sub_departments_of'                    => ['en' => 'Sub-departments of', 'fr' => 'Sous-structures de'],
    'pages.tags_page.confirm'                     => ['en' => 'Confirm', 'fr' => 'Confirmer'],
    'pages.tags_page.create_new'                  => ['en' => 'Create tag', 'fr' => 'Créer un tag'],
    'pages.tags_page.delete_body'                 => ['en' => 'Delete this tag permanently?', 'fr' => 'Supprimer définitivement ce tag ?'],
    'pages.tags_page.delete_title'                => ['en' => 'Delete tag', 'fr' => 'Supprimer le tag'],
    'pages.tags_page.edit'                        => ['en' => 'Edit', 'fr' => 'Modifier'],
    'pages.tags_page.existing'                    => ['en' => 'Existing tags', 'fr' => 'Tags existants'],
    'pages.tags_page.manage'                      => ['en' => 'Manage', 'fr' => 'Gérer'],
    'pages.tags_page.tag_name'                    => ['en' => 'Tag name', 'fr' => 'Nom du tag'],
    'pages.total'                                 => ['en' => 'Total', 'fr' => 'Total'],
    'pages.translations.actions'                  => ['en' => 'Actions', 'fr' => 'Actions'],
    'pages.translations.add_button'               => ['en' => 'Add', 'fr' => 'Ajouter'],
    'pages.translations.arabic'                   => ['en' => 'Arabic', 'fr' => 'Arabe'],
    'pages.translations.branding'                 => ['en' => 'Branding', 'fr' => 'Image de marque'],
    'pages.translations.current'                  => ['en' => 'Current', 'fr' => 'Actuel'],
    'pages.translations.enable_rtl'               => ['en' => 'Enable RTL', 'fr' => 'Activer RTL'],
    'pages.translations.english'                  => ['en' => 'English', 'fr' => 'Anglais'],
    'pages.translations.filter'                   => ['en' => 'Filter', 'fr' => 'Filtrer'],
    'pages.translations.french'                   => ['en' => 'French', 'fr' => 'Français'],
    'pages.translations.groups_description.actions'   => ['en' => 'Action buttons', 'fr' => "Boutons d'action"],
    'pages.translations.groups_description.auth'      => ['en' => 'Authentication screens', 'fr' => "Écrans d'authentification"],
    'pages.translations.groups_description.filters'   => ['en' => 'Filter labels', 'fr' => 'Libellés de filtres'],
    'pages.translations.groups_description.header'    => ['en' => 'Header elements', 'fr' => "Éléments d'en-tête"],
    'pages.translations.groups_description.nav'       => ['en' => 'Navigation menu', 'fr' => 'Menu de navigation'],
    'pages.translations.groups_description.pages'     => ['en' => 'Page content', 'fr' => 'Contenu des pages'],
    'pages.translations.groups_description.tables'    => ['en' => 'Table headers', 'fr' => 'En-têtes de tableaux'],
    'pages.translations.groups_description.validation'=> ['en' => 'Validation messages', 'fr' => 'Messages de validation'],
    'pages.translations.groups_title'             => ['en' => 'Groups', 'fr' => 'Groupes'],
    'pages.translations.header_logo'              => ['en' => 'Header logo', 'fr' => 'Logo en-tête'],
    'pages.translations.help_note'                => ['en' => 'Translations marked as overridden take priority over defaults.', 'fr' => 'Les traductions marquées comme modifiées ont priorité sur les valeurs par défaut.'],
    'pages.translations.image_limit_5mb'          => ['en' => 'Max 5 MB', 'fr' => 'Max 5 Mo'],
    'pages.translations.image_limit_8mb'          => ['en' => 'Max 8 MB', 'fr' => 'Max 8 Mo'],
    'pages.translations.introduction'             => ['en' => 'Manage interface translations.', 'fr' => "Gérez les traductions de l'interface."],
    'pages.translations.key_defined_by_developers'=> ['en' => 'Key defined by developers', 'fr' => 'Clé définie par les développeurs'],
    'pages.translations.language'                 => ['en' => 'Language', 'fr' => 'Langue'],
    'pages.translations.limit_reached'            => ['en' => 'Limit reached', 'fr' => 'Limite atteinte'],
    'pages.translations.login_left_image'         => ['en' => 'Login image', 'fr' => 'Image de connexion'],
    'pages.translations.max_users'                => ['en' => 'Max users', 'fr' => 'Utilisateurs max'],
    'pages.translations.max_users_help'           => ['en' => '0 = unlimited', 'fr' => '0 = illimité'],
    'pages.translations.overridden'               => ['en' => 'Overridden', 'fr' => 'Modifié'],
    'pages.translations.revert_confirm'           => ['en' => 'Revert to default?', 'fr' => 'Revenir à la valeur par défaut ?'],
    'pages.translations.revert_to_default'        => ['en' => 'Revert to default', 'fr' => 'Revenir à la valeur par défaut'],
    'pages.translations.rtl_title'                => ['en' => 'RTL mode', 'fr' => 'Mode RTL'],
    'pages.translations.save_override'            => ['en' => 'Save override', 'fr' => 'Enregistrer la modification'],
    'pages.translations.save_override_hint'       => ['en' => 'This will override the default translation.', 'fr' => 'Cela remplacera la traduction par défaut.'],
    'pages.translations.search_placeholder'       => ['en' => 'Search translations…', 'fr' => 'Rechercher des traductions…'],
    'pages.translations.select_timezone'          => ['en' => 'Select timezone', 'fr' => 'Sélectionner le fuseau horaire'],
    'pages.translations.show_missing_only'        => ['en' => 'Missing only', 'fr' => 'Manquantes uniquement'],
    'pages.translations.slots_remaining'          => ['en' => 'Slots remaining', 'fr' => 'Places restantes'],
    'pages.translations.status'                   => ['en' => 'Status', 'fr' => 'Statut'],
    'pages.translations.timezone'                 => ['en' => 'Timezone', 'fr' => 'Fuseau horaire'],
    'pages.translations.using_default'            => ['en' => 'Default', 'fr' => 'Par défaut'],
    'pages.translations.zero_unlimited_ph'        => ['en' => '0 = unlimited', 'fr' => '0 = illimité'],
    'pages.uncategorized'                         => ['en' => 'Uncategorized', 'fr' => 'Sans catégorie'],
    'pages.upload.attach_document'                => ['en' => 'Attach document', 'fr' => 'Joindre un document'],
    'pages.upload.browse_file'                    => ['en' => 'Browse file', 'fr' => 'Parcourir'],
    'pages.upload.created_by'                     => ['en' => 'Created by', 'fr' => 'Créé par'],
    'pages.upload.creation_date'                  => ['en' => 'Creation date', 'fr' => 'Date de création'],
    'pages.upload.delete'                         => ['en' => 'Delete', 'fr' => 'Supprimer'],
    'pages.upload.document_info'                  => ['en' => 'Document info', 'fr' => 'Info document'],
    'pages.upload.document_information'           => ['en' => 'Document information', 'fr' => 'Informations du document'],
    'pages.upload.document_title'                 => ['en' => 'Document title', 'fr' => 'Titre du document'],
    'pages.upload.drag_drop_here'                 => ['en' => 'Drag and drop here', 'fr' => 'Glissez-déposez ici'],
    'pages.upload.enter_tags_comma'               => ['en' => 'Enter tags separated by commas', 'fr' => 'Entrez les tags séparés par des virgules'],
    'pages.upload.expire_date'                    => ['en' => 'Expiration date', 'fr' => "Date d'expiration"],
    'pages.upload.expires_at'                     => ['en' => 'Expires at', 'fr' => 'Expire le'],
    'pages.upload.file_preview'                   => ['en' => 'File preview', 'fr' => 'Aperçu du fichier'],
    'pages.upload.file_preview_fallback'          => ['en' => 'Preview not available.', 'fr' => 'Aperçu non disponible.'],
    'pages.upload.file_sent_successfully'         => ['en' => 'File sent successfully.', 'fr' => 'Fichier envoyé avec succès.'],
    'pages.upload.file_type'                      => ['en' => 'File type', 'fr' => 'Type de fichier'],
    'pages.upload.file_type_not_supported'        => ['en' => 'File type not supported.', 'fr' => 'Type de fichier non supporté.'],
    'pages.upload.image_preview'                  => ['en' => 'Image preview', 'fr' => 'Aperçu image'],
    'pages.upload.max_batch_info'                 => ['en' => 'Max files per upload', 'fr' => 'Fichiers max par dépôt'],
    'pages.upload.max_file_size'                  => ['en' => 'Max file size', 'fr' => 'Taille max du fichier'],
    'pages.upload.metadata_updated'               => ['en' => 'Metadata updated.', 'fr' => 'Métadonnées mises à jour.'],
    'pages.upload.no_preview'                     => ['en' => 'No preview available.', 'fr' => 'Aucun aperçu disponible.'],
    'pages.upload.open_in_new_tab'                => ['en' => 'Open in new tab', 'fr' => 'Ouvrir dans un nouvel onglet'],
    'pages.upload.organizational_structure'       => ['en' => 'Organizational structure', 'fr' => 'Structure organisationnelle'],
    'pages.upload.pdf_preview'                    => ['en' => 'PDF preview', 'fr' => 'Aperçu PDF'],
    'pages.upload.physical_location'              => ['en' => 'Physical location', 'fr' => 'Emplacement physique'],
    'pages.upload.pole'                           => ['en' => 'Pole', 'fr' => 'Pôle'],
    'pages.upload.preview'                        => ['en' => 'Preview', 'fr' => 'Aperçu'],
    'pages.upload.remove'                         => ['en' => 'Remove', 'fr' => 'Retirer'],
    'pages.upload.review_status_message'          => ['en' => 'This document is pending review.', 'fr' => "Ce document est en attente d'approbation."],
    'pages.upload.select_folder'                  => ['en' => 'Select folder', 'fr' => 'Sélectionner un dossier'],
    'pages.upload.select_room_first'              => ['en' => 'Select a room first.', 'fr' => "Sélectionnez d'abord une salle."],
    'pages.upload.service'                        => ['en' => 'Service', 'fr' => 'Service'],
    'pages.upload.sub_department'                 => ['en' => 'Sub-department', 'fr' => 'Sous-structure'],
    'pages.upload.upload_new_version_for'         => ['en' => 'Upload new version for', 'fr' => 'Déposer une nouvelle version pour'],
    'pages.user_fields.'                          => ['en' => '', 'fr' => ''],
    'pages.user_fields.service_id'                => ['en' => 'Service', 'fr' => 'Service'],
    'pages.user_fields.sub_department_id'         => ['en' => 'Sub-department', 'fr' => 'Sous-structure'],
    'pages.users_page.add_user_limit_reached_title'=> ['en' => 'Limit reached', 'fr' => 'Limite atteinte'],
    'pages.users_page.delete_user_title'          => ['en' => 'Delete user', 'fr' => "Supprimer l'utilisateur"],
    'pages.versions.creation_date'                => ['en' => 'Creation date', 'fr' => 'Date de création'],
    'pages.workflow.manage_for'                   => ['en' => 'Manage workflow for', 'fr' => 'Gérer le workflow de'],
    'passwords.sent'                              => ['en' => 'Password reset link sent.', 'fr' => 'Lien de réinitialisation envoyé.'],
    'tables.pagination.showing'                   => ['en' => 'Showing :from to :to of :total results', 'fr' => 'Affichage de :from à :to sur :total résultats'],
];

$host = '127.0.0.1';
$db   = 'locaged_spcr';
$user = 'locaged_v2';
$pass = 'gizWEizICcW3J5JDQqJwnAQZ';

try {
    $pdo = new PDO("mysql:host=$host;dbname=$db;charset=utf8mb4", $user, $pass, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
    ]);
} catch (Exception $e) {
    die("DB connection failed: " . $e->getMessage() . "\n");
}

$stmt = $pdo->prepare("
    INSERT INTO ui_translations (`key`, en_text, fr_text)
    VALUES (:key, :en, :fr)
    ON DUPLICATE KEY UPDATE en_text = VALUES(en_text), fr_text = VALUES(fr_text)
");

$count = 0;
foreach ($translations as $key => $texts) {
    $stmt->execute([':key' => $key, ':en' => $texts['en'], ':fr' => $texts['fr']]);
    $count++;
}

echo "OK $count traductions inserees/mises a jour.\n";
